fix snap install. rm superflous juptyer stuff on the jupyterhub hub. fix(?) conda env setup.

diff --git a/user-notebook/Dockerfile b/user-notebook/Dockerfile
--- a/user-notebook/Dockerfile
+++ b/user-notebook/Dockerfile
@@ -2,8 +2,10 @@ FROM quay.io/jupyter/scipy-notebook:latest
 
 COPY environment.yml /tmp/environment.yml
 
-# Install conda env
-RUN conda env create -f /tmp/environment.yml && \
+# Set up conda-forge and install environment
+RUN conda config --add channels conda-forge && \
+    conda config --set channel_priority strict && \
+    conda env create -f /tmp/environment.yml && \
     conda clean -afy
 
 # Optional: activate environment by default
@@ -13,15 +15,18 @@ RUN echo "conda activate planetary-env" >> ~/.bashrc
 ENV CONDA_DEFAULT_ENV=planetary-env
 ENV PATH="/opt/conda/envs/planetary-env/bin:$PATH"
 
-# create symlinks for user data directories
-# NOTE: if you edit these you must edit juptyer/jupyterhub_config.py c.DockerSpawner.volumes too
+# Create symlinks for user data directories
+# NOTE: If you edit these, you must also update jupyterhub_config.py (c.DockerSpawner.volumes)
 RUN ln -s /srv/pgs /home/jovyan/pgs && \
     ln -s /srv/yin /home/jovyan/yin
 
 # ==============================================================================================
-# === install ESA SNAP
+# === Install ESA SNAP
 # ==============================================================================================
+# NOTE: This will **always** return success.
+#       The installer could fail silently.
+#       This is done because the installer returns 1 even when it is successful.
 RUN wget https://download.esa.int/step/snap/10_0/installers/esa-snap_sentinel_linux-10.0.0.sh && \
     chmod +x ./esa-snap_sentinel_linux-10.0.0.sh && \
-    printf "o\n2\n/opt/esa-snap\nx,4\ny\n/usr/local/bin\nn\n" | ./esa-snap_sentinel_linux-10.0.0.sh
+    printf "o\n2\n/home/jovyan/esa-snap\nx,4\ny\n/usr/local/bin\nn\n" | ./esa-snap_sentinel_linux-10.0.0.sh || true
 # ==============================================================================================
